# docker-compose.yml
version: "3.9"

services:
  svelte-app:
    build: .
    ports:
      - "5173:5173"
    # Load environment variables from your .env or local.env file
    env_file:
      - .env.local  # or .env, whichever name you used
    command: npm run dev -- --host 0.0.0.0
